version: '3.6'
services:
  flask:
    build: ./app/.
    depends_on:
      - database
    ports:
      - 5000:5000

  database:
    image: postgres:10.5
    restart: always
    environment: 
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD=database
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5431:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./db/psql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./db/psql/insert_tables.sql:/docker-entrypoint-initdb.d/insert_tables.sql
